### ISSUE TITLE
(T) Неправильно считается Experience в классе Driver

### ISSUE THREAD

**Issue by ikit-mita** [Snatch3000/HW2#1]
Если права выданы 30 декабря 2014, то 1 год опыта должен быть 30 декабря 2015, а не 1 января 2015. Можешь считать, что в любом году 365 дней.

И что ты хотел сделать здесь?

```
_experience = int.Parse((d2.Year - d1.Year).ToString());
```

Вычитая 2 значения типа int ты и так получаешь int, к чему тут ToString и Parse?
- нет смысла в поле _experience. Его надо убрать

**Comment by Snatch3000** [comment]
Сделано
