### ISSUE TITLE
(Т) Неправильная работа с исключениями

### ISSUE THREAD

**Issue by ikit-mita** [Snatch3000/HW2#3]
> a. Объекты модели **не должны выводить сообщения (об ошибках) на консоль**, а 
> должны кидать исключения, которые обрабатываются на UI, где и выводится сообщение;

Метод Car.ChangeOwner обрабатывать исключение и выводить сообщение об ошибке, Это должно происходить на View

**Comment by Snatch3000** [comment]
Сделано
